
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table2;
	private global::Gtk.Entry entry1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label label3;
	private global::Gtk.Label labelResult;
	private global::Gtk.Label primero;
	private global::Gtk.Label segundo;
	private global::Gtk.Table table1;
	private global::Gtk.Button buttonIgual;
	private global::Gtk.Button buttonReset;
	private global::Gtk.Table table3;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Button button4;
	private global::Gtk.Button button5;
	private global::Gtk.Button button6;
	private global::Gtk.Button button7;
	private global::Gtk.Button button8;
	private global::Gtk.Button button9;
	private global::Gtk.Button buttonCero;
	private global::Gtk.Button buttonComa;
	private global::Gtk.Button buttonDiv;
	private global::Gtk.Button buttonMasMenos;
	private global::Gtk.Button buttonMultip;
	private global::Gtk.Button buttonResta;
	private global::Gtk.Button buttonSuma;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.table2.Add (this.entry1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry1]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.table2.Add (this.entry2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry2]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Tu resultado:");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.labelResult = new global::Gtk.Label ();
		this.labelResult.Name = "labelResult";
		this.labelResult.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.table2.Add (this.labelResult);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelResult]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.primero = new global::Gtk.Label ();
		this.primero.Name = "primero";
		this.primero.LabelProp = global::Mono.Unix.Catalog.GetString ("Primer operando:");
		this.table2.Add (this.primero);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.primero]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.segundo = new global::Gtk.Label ();
		this.segundo.Name = "segundo";
		this.segundo.LabelProp = global::Mono.Unix.Catalog.GetString ("Segundo operando:");
		this.table2.Add (this.segundo);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.segundo]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.buttonIgual = new global::Gtk.Button ();
		this.buttonIgual.CanFocus = true;
		this.buttonIgual.Name = "buttonIgual";
		this.buttonIgual.UseUnderline = true;
		this.buttonIgual.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.table1.Add (this.buttonIgual);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonIgual]));
		w8.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table1.Gtk.Table+TableChild
		this.buttonReset = new global::Gtk.Button ();
		this.buttonReset.CanFocus = true;
		this.buttonReset.Name = "buttonReset";
		this.buttonReset.UseUnderline = true;
		this.buttonReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.table1.Add (this.buttonReset);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonReset]));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.FocusOnClick = false;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table3.Add (this.button1);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.button1]));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.FocusOnClick = false;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table3.Add (this.button2);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.button2]));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.FocusOnClick = false;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.table3.Add (this.button3);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.button3]));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.FocusOnClick = false;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.table3.Add (this.button4);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.button4]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.FocusOnClick = false;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.table3.Add (this.button5);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.button5]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.FocusOnClick = false;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.table3.Add (this.button6);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.button6]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.FocusOnClick = false;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.table3.Add (this.button7);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.button7]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.FocusOnClick = false;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.table3.Add (this.button8);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.button8]));
		w18.TopAttach = ((uint)(2));
		w18.BottomAttach = ((uint)(3));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.FocusOnClick = false;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.table3.Add (this.button9);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.button9]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonCero = new global::Gtk.Button ();
		this.buttonCero.CanFocus = true;
		this.buttonCero.Name = "buttonCero";
		this.buttonCero.UseUnderline = true;
		this.buttonCero.FocusOnClick = false;
		this.buttonCero.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.buttonCero);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonCero]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonComa = new global::Gtk.Button ();
		this.buttonComa.CanFocus = true;
		this.buttonComa.Name = "buttonComa";
		this.buttonComa.UseUnderline = true;
		this.buttonComa.FocusOnClick = false;
		this.buttonComa.Label = global::Mono.Unix.Catalog.GetString (",");
		this.table3.Add (this.buttonComa);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonComa]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonDiv = new global::Gtk.Button ();
		this.buttonDiv.CanFocus = true;
		this.buttonDiv.Name = "buttonDiv";
		this.buttonDiv.UseUnderline = true;
		this.buttonDiv.Label = global::Mono.Unix.Catalog.GetString ("División");
		this.table3.Add (this.buttonDiv);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonDiv]));
		w22.TopAttach = ((uint)(3));
		w22.BottomAttach = ((uint)(4));
		w22.LeftAttach = ((uint)(3));
		w22.RightAttach = ((uint)(4));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonMasMenos = new global::Gtk.Button ();
		this.buttonMasMenos.CanFocus = true;
		this.buttonMasMenos.Name = "buttonMasMenos";
		this.buttonMasMenos.UseUnderline = true;
		this.buttonMasMenos.FocusOnClick = false;
		this.buttonMasMenos.Label = global::Mono.Unix.Catalog.GetString ("+/-");
		this.table3.Add (this.buttonMasMenos);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonMasMenos]));
		w23.TopAttach = ((uint)(3));
		w23.BottomAttach = ((uint)(4));
		w23.LeftAttach = ((uint)(2));
		w23.RightAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonMultip = new global::Gtk.Button ();
		this.buttonMultip.CanFocus = true;
		this.buttonMultip.Name = "buttonMultip";
		this.buttonMultip.UseUnderline = true;
		this.buttonMultip.Label = global::Mono.Unix.Catalog.GetString ("Multiplicación");
		this.table3.Add (this.buttonMultip);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonMultip]));
		w24.TopAttach = ((uint)(2));
		w24.BottomAttach = ((uint)(3));
		w24.LeftAttach = ((uint)(3));
		w24.RightAttach = ((uint)(4));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonResta = new global::Gtk.Button ();
		this.buttonResta.CanFocus = true;
		this.buttonResta.Name = "buttonResta";
		this.buttonResta.UseUnderline = true;
		this.buttonResta.Label = global::Mono.Unix.Catalog.GetString ("Resta");
		this.table3.Add (this.buttonResta);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonResta]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(3));
		w25.RightAttach = ((uint)(4));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonSuma = new global::Gtk.Button ();
		this.buttonSuma.CanFocus = true;
		this.buttonSuma.Name = "buttonSuma";
		this.buttonSuma.UseUnderline = true;
		this.buttonSuma.Label = global::Mono.Unix.Catalog.GetString ("Suma");
		this.table3.Add (this.buttonSuma);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonSuma]));
		w26.LeftAttach = ((uint)(3));
		w26.RightAttach = ((uint)(4));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table3);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
		w27.PackType = ((global::Gtk.PackType)(1));
		w27.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 461;
		this.DefaultHeight = 312;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
